services:
  postgres:
    image: postgres:16-alpine
    container_name: lodgekey-postgres
    environment:
      POSTGRES_USER: lodgekey_user
      POSTGRES_PASSWORD: lodgekey_password
      POSTGRES_DB: lodgekey_dev
    ports:
      - "5433:5432"
    volumes:
      - lodgekey_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: lodgekey-redis
    ports:
      - "6379:6379"

  pgadmin:
    image: dpage/pgadmin4
    container_name: lodgekey-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@lodgekey.dev
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  mailhog:
    image: mailhog/mailhog
    container_name: lodgekey-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  redis-commander:
    image: rediscommander/redis-commander
    container_name: lodgekey-redis-commander
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis

volumes:
  lodgekey_pgdata:
